spring:
  application:
    name: exchange-rate
  datasource:
    url: jdbc:h2:mem:ratedb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

